sonar.projectKey=devpro_sast-samples-php
sonar.projectName=sast-samples / php-symfony
sonar.sources=src
sonar.tests=tests
sonar.language=php
sonar.php.version=8.3
# sonar.host.url=http://localhost:9000   # uncomment for self-hosted SonarQube
