#!/usr/bin/env node
//
// Generate docs/matrix.md from results/scores.json.
//
// The matrix is never edited by hand.
// When the table and the SARIF files disagree, the SARIF files are right: run 'task score' and commit the regenerated table.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { REPO_ROOT, RESULTS_DIR, loadSamples } from "./bench.mjs";

const SYMBOL = { detected: "yes", partial: "partial", missed: "no" };

const DIFFICULTY_LABEL = {
  1: "1 syntax",
  2: "2 intra-procedural",
  3: "3 cross-function",
  4: "4 cross-file",
  5: "5 framework or sanitizer",
};

/**
 * Render a Markdown table with every pipe aligned.
 *
 * markdownlint enforces the aligned style, so the generator has to pad cells rather than emit them compactly.
 */
function table(header, rows) {
  const widths = header.map((cell, index) =>
    Math.max(cell.length, ...rows.map((row) => String(row[index] ?? "").length)),
  );
  const line = (cells) => cells.map((cell, index) => String(cell ?? "").padEnd(widths[index])).join(" | ").trimEnd();
  return [line(header), widths.map((width) => "-".repeat(width)).join("-|-"), ...rows.map(line)];
}

const scoresPath = join(RESULTS_DIR, "scores.json");
if (!existsSync(scoresPath)) {
  console.error("results/scores.json not found, run: task score");
  process.exit(1);
}

const report = JSON.parse(readFileSync(scoresPath, "utf8"));
const casesById = new Map();
for (const sample of loadSamples()) {
  for (const kase of sample.cases) casesById.set(kase.id, kase);
}

function renderSample(entry) {
  const lines = [`## ${entry.sample}`, "", entry.title, ""];
  const tools = Object.keys(entry.tools);

  if (!tools.length) {
    lines.push(
      "No scan results committed yet.",
      `Run \`task scan:sample SAMPLE=${entry.sample}\` then \`task score\`.`,
      "",
    );
    return lines;
  }

  const caseRows = [];
  for (const [id, kase] of casesById) {
    if (!id.startsWith(`${entry.sample}/`)) continue;
    caseRows.push([
      `[${kase.name}](../samples/${entry.sample}/cases/${kase.name}/)`,
      DIFFICULTY_LABEL[kase.difficulty],
      kase.cwe.join(", "),
      String(kase.expected.length),
    ]);
  }
  lines.push("### Cases", "", ...table(["Case", "Difficulty", "CWE", "Expected findings"], caseRows), "");

  const detectionRows = [];
  const reference = entry.tools[tools[0]];
  reference.cases.forEach((caseScore, caseIndex) => {
    const kase = casesById.get(caseScore.case);
    caseScore.outcomes.forEach((outcome, outcomeIndex) => {
      const cells = tools.map((tool) => SYMBOL[entry.tools[tool].cases[caseIndex].outcomes[outcomeIndex].status]);
      detectionRows.push([kase.name, outcome.expectation, outcome.requires, ...cells]);
    });
  });
  lines.push(
    "### Detection by expectation",
    "",
    ...table(["Case", "Expectation", "Requires", ...tools], detectionRows),
    "",
  );

  const totalRows = tools.map((tool) => {
    const t = entry.tools[tool].totals;
    return [
      tool,
      entry.tools[tool].version ?? "unknown",
      `${t.detected}/${t.expected}`,
      String(t.partial),
      String(t.missed),
      t.recall === null ? "n/a" : `${Math.round(t.recall * 100)}%`,
      String(t.false_positives),
      String(t.unexpected),
    ];
  });
  lines.push(
    "### Totals",
    "",
    ...table(["Tool", "Version", "Detected", "Partial", "Missed", "Recall", "False positives", "Unexpected"], totalRows),
    "",
  );
  return lines;
}

const lines = [
  "# Detection matrix",
  "",
  "Generated by `scripts/render_matrix.mjs` from the SARIF files committed under `results/`.",
  "Do not edit by hand.",
  "",
  "`yes` means the tool reported a finding on the expected location with a matching CWE.",
  "`partial` means it reported something there under an unrelated rule or with no CWE at all.",
  "`no` means nothing was reported within the tolerance window.",
  "",
  "False positives are findings inside the safe counterpart of a case.",
  "Unexpected findings are everything else the tool reported in the sample, listed for information and not counted against it.",
  "",
  "See [methodology.md](methodology.md) for the full scoring rules.",
  "",
];

for (const entry of report.samples) lines.push(...renderSample(entry));

const output = join(REPO_ROOT, "docs", "matrix.md");
writeFileSync(output, `${lines.join("\n").trimEnd()}\n`, "utf8");
console.log("Wrote docs/matrix.md");
