name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  php-symfony-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: php-symfony

    steps:
      - uses: actions/checkout@v4

      # TODO
      # - name: Setup PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: "8.3"
      #     tools: composer:v2

      # - name: Install dependencies
      #   run: composer install --prefer-dist --no-progress

      # - name: Run tests
      #   run: vendor/bin/phpunit

  # sonar:
  #   runs-on: ubuntu-latest
  #   needs: php-symfony-tests
  #   defaults:
  #     run:
  #       working-directory: php-symfony

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: SonarCloud scan
  #       uses: SonarSource/sonarcloud-github-action@v3
  #       with:
  #         projectBaseDir: php-symfony
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
